export { default as AccountAddressPage } from './address.vue'
export { default as AccountCreateAddressPage } from './createAddress.vue'
export { default as AccountEditAddressPage } from './editAddress.vue'
export * from './edit'
export * from './login'
export * from './register'
export * from './password'
export * from './account'
