export { default as ErrorTemplate } from './error.vue'
export { default as FooterTemplate } from './footer.vue'
export { default as HeaderTemplate } from './header.vue'
export { default as LayoutTemplate } from './layout.vue'
export * from './page'
