export { default as AccountAddress } from './address.vue'
export { default as AccountCreateAddress } from './createAddress.vue'
export { default as AccountEdit } from './edit.vue'
export { default as AccountEditAddress } from './editAddress.vue'
export { default as AccountLogin } from './login.vue'
export { default as AccountNew } from './new.vue'
export { default as AccountPassword } from './password.vue'
export { default as AccountRegister } from './register.vue'
