export { default as CategoryModule } from './category.vue'
export { default as CheckoutModule } from './checkout.vue'
export { default as FeaturedProductModule } from './featuredProduct.vue'
export { default as LatestProductModule } from './latestProduct.vue'
export { default as RelatedProductModule } from './relatedProduct.vue'
export { default as SearchProductModule } from './searchProduct.vue'
export { default as SpecialProductModule } from './specialProduct.vue'
