module.exports = {
  CommonDeprecatedApi: "templates/common/deprecated-api/deprecated-api.vue",
  StoreCheckoutSuccess: "templates/store/checkout-success/checkout-success.vue",
  CommonLayout: "templates/common/layout/layout.vue",
  LayoutDefault: "templates/layouts/default/default.vue",
  LayoutFullWidth: "templates/layouts/fullWidth/fullWidth.vue",
  AccountAccount: "templates/account/account/account.vue",
  AccountAddress: "templates/account/address/address.vue",
  AccountAddressCreate: "templates/account/addressCreate/addressCreate.vue",
  AccountAddressEdit: "templates/account/addressEdit/addressEdit.vue",
  AccountEdit: "templates/account/edit/edit.vue",
  AccountLogin: "templates/account/login/login.vue",
  AccountPassword: "templates/account/password/password.vue",
  AccountRegister: "templates/account/register/register.vue",
  AccountSuccess: "templates/account/success/success.vue",
  BlogCategory: "templates/blog/category/category.vue",
  BlogPost: "templates/blog/post/post.vue",
  CommonContact: "templates/common/contact/contact.vue",
  CommonError: "templates/common/error/error.vue",
  CommonPage: "templates/common/page/page.vue",
  CommonSearch: "templates/common/search/search.vue",
  StoreCart: "templates/store/cart/cart.vue",
  StoreCategory: "templates/store/category/category.vue",
  StoreManufacturer: "templates/store/manufacturer/manufacturer.vue",
  StoreManufacturerList:
    "templates/store/manufacturerList/manufacturerList.vue",
  StoreCompare: "templates/store/compare/compare.vue",
  StoreProduct: "templates/store/product/product.vue",
  StoreSpecial: "templates/store/special/special.vue",
  StoreWishlist: "templates/store/wishlist/wishlist.vue",
};
