export { default as AccountModule } from './account.vue'
export { default as AccountLinksModule } from './accountLinks.vue'
export { default as ExtraLinksModule } from './extraLinks.vue'
export { default as MenuModule } from './menu.vue'
export { default as PagesModule } from './pages.vue'
export { default as SearchModule } from './search.vue'
export { default as SlideshowModule } from './slideshow.vue'
